### ISSUE TITLE
Missing IPv6 support

### ISSUE THREAD

**Issue by Joyez** [SECFORCE/sparta#11]
It seems that SPARTA do not fully support IPv6,
when adding an IPv6 address in the scope we got an **Invalid Input**;
and when importing an nmap xml file including an IPv6 host only, nmap scans fails to launch and the IPv6 address is not even shown in the *Information* tab.

```
[+] Parsing nmap xml file: /root/Desktop/jason6.xml
	[+] Finished in 0.0682790279388 seconds.
Traceback (most recent call last):
  File "/root/sparta/ui/view.py", line 1125, in updateInterface
    self.updateHostsTableView()
  File "/root/sparta/ui/view.py", line 851, in updateHostsTableView
    self.HostsTableModel.sort(3, Qt.DescendingOrder)
  File "/root/sparta/app/hostmodels.py", line 124, in sort
    array.append(IP2Int(self.__hosts[i]['ip']))
  File "/root/sparta/app/auxiliary.py", line 37, in IP2Int
    o = map(int, ip.split('.'))
ValueError: invalid literal for int() with base 10: ''
```

:)

**Comment by st3r30byt3** [comment]
Hi Joyez! Thanks. We know! :)
This is in our TODO list with a low priority. This priority could change if we have many requests for this.

**Comment by PowerPress** [comment]
This is a great idea please implement

**Comment by st3r30byt3** [comment]
The main problem here is that most tools that we'd want to run after nmap don't support IPv6. This will lead to several problems.
