### ISSUE TITLE
Nikto process is done

### ISSUE THREAD

**Issue by Bo0oM** [SECFORCE/sparta#24]
```bash
[+] The process is done!
Traceback (most recent call last):
  File "/usr/share/sparta/ui/view.py", line 889, in updateToolsTableView
  File "/usr/share/sparta/controller/controller.py", line 444, in getProcessesFromDB
  File "/usr/share/sparta/app/logic.py", line 353, in getProcessesFromDB
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2446, in execute
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2490, in contextual_connect
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 224, in connect
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 387, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 802, in _do_get
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 188, in _create_connection
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 270, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 330, in __connect
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 80, in connect
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 281, in connect
sqlalchemy.exc.OperationalError: (OperationalError) unable to open database file None None
	[+] The process is done!
	[+] The process is done!
Traceback (most recent call last):
  File "/usr/share/sparta/ui/view.py", line 889, in updateToolsTableView
  File "/usr/share/sparta/controller/controller.py", line 444, in getProcessesFromDB
  File "/usr/share/sparta/app/logic.py", line 353, in getProcessesFromDB
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2446, in execute
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2490, in contextual_connect
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 224, in connect
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 387, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 802, in _do_get
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 188, in _create_connection
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 270, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 330, in __connect
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 80, in connect
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 281, in connect
sqlalchemy.exc.OperationalError: (OperationalError) unable to open database file None None
```

**Comment by st3r30byt3** [comment]
Thanks Dmitry. Any more details? Unfortunately, this is not enough to replicate. Looks like the DB got corrupted somehow.

**Comment by st3r30byt3** [comment]
Closed for lack of info. Please reopen if necessary.
