### ISSUE TITLE
sqlalchemy issues

### ISSUE THREAD

**Issue by giveen** [SECFORCE/sparta#30]
Python 2.7.6

Linux ubuntu 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Traceback (most recent call last):
  File "sparta.py", line 83, in <module>
    controller = Controller(view, logic)			# Controller prep (communication between model and view)
  File "/usr/share/sparta/controller/controller.py", line 34, in __init__
    self.start()										# initialisations (globals, etc)
  File "/usr/share/sparta/controller/controller.py", line 46, in start
    self.view.start(title)
  File "/usr/share/sparta/ui/view.py", line 89, in start
    self.updateInterface()
  File "/usr/share/sparta/ui/view.py", line 1130, in updateInterface
    self.updateServiceNamesTableView()
  File "/usr/share/sparta/ui/view.py", line 868, in updateServiceNamesTableView
    self.ServiceNamesTableModel = ServiceNamesTableModel(self.controller.getServiceNamesFromDB(self.filters), headers)
  File "/usr/share/sparta/controller/controller.py", line 401, in getServiceNamesFromDB
    return self.logic.getServiceNamesFromDB(filters)
  File "/usr/share/sparta/app/logic.py", line 214, in getServiceNamesFromDB
    return metadata.bind.execute(tmp_query).fetchall()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2447, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1449, in execute
    params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1628, in _execute_text
    statement, parameters
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1698, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1691, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 331, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (OperationalError) no such table: db_tables_nmap_service "SELECT DISTINCT service.name FROM db_tables_nmap_service as service INNER JOIN db_tables_nmap_port as ports INNER JOIN db_tables_nmap_host AS hosts ON hosts.id = ports.host_id AND service.id=ports.service_id WHERE 1=1 AND hosts.status!='down' AND ports.state!='closed' AND ports.state!='filtered' AND ports.state!='open|filtered' ORDER BY service.name ASC" ()

I resolved this by forcing a sqlalchemy upgrade with
sudo pip install SQLAlchemy --upgrade

**Comment by st3r30byt3** [comment]
Glad you could solve the problem. :) 
Note that SPARTA was tested on Kali Linux and the following versions:
python 2.7.3
elixir 0.7.1-1
sqlalchemy 0.7.8-1

Please let us know if you have any other issues.

**Comment by adamziaja** [comment]
```
apt-get update && apt-get install python-elixir nmap hydra cutycapt ldap-utils rwho rsh-client x11-apps finger -y && git clone https://github.com/secforce/sparta.git
```
if you will have any problems then
```
apt-get install -f
```
